export OP_ACCOUNT := "my.1password.com"

verify-artifact:
    dagger call verify-artifact

# Deploy to Fly.io
deploy:
    dagger call deploy \
      --ghcr-token='cmd:gh auth token | tr -d '\''\n'\''' \
      --flyio-app=miele-delay-start \
      --flyio-token='cmd:op read "op://Private/Fly.io API token for miele-delay-start/password" | tr -d '\''\n'\''' \
      --flyio-region=arn
