# Deploy miele delay-start app to Fly.io
deploy:
    dagger call --mod ./miele-ci deploy \
      --ghcr-token='cmd:gh auth token | tr -d '\''\n'\''' \
      --flyio-app=miele-delay-start \
      --flyio-token='cmd:op read "op://Private/Fly.io API Token/credential" | tr -d '\''\n'\''' \
      --flyio-region=arn
