name: Generate Terraform Documentation

on:
  workflow_dispatch:

jobs:

  terraform-docs:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Generate Terraform docs
        uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
        with:
          version: latest
          verb: call
          args: terraform-docs export --path ./fixtures/terraform
