terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Provider configuration will be auto-generated by terraform-local

# Create an S3 bucket
resource "aws_s3_bucket" "demo" {
  bucket = "demo-bucket"
}

# Output the bucket name
output "bucket_name" {
  value       = aws_s3_bucket.demo.bucket
  description = "The name of the S3 bucket"
}

output "bucket_arn" {
  value       = aws_s3_bucket.demo.arn
  description = "The ARN of the S3 bucket"
}
